#!/usr/bin/env bash

# Update the package list and install Nginx
sudo apt update
sudo apt install nginx -y

# Get the current hostname
server_hostname=$(hostname)

# Create a custom Nginx configuration file for the custom header
cat <<EOF | sudo tee /etc/nginx/sites-available/custom_header
server {
    listen 80 default_server;
    server_name _;

    location / {
        add_header X-Served-By $server_hostname;
        # Your existing Nginx configuration directives go here
    }
}
